# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='data_de_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='data_de_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de in\xedcio do servi\xe7o'),
        ),
    ]
