# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, verbose_name='descricao'),
        ),
    ]
