# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.BooleanField(default=False, verbose_name='concluido'),
        ),
    ]
