# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.BigIntegerField(unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='sobrenome')),
                ('codigo', models.CharField(help_text='Ex.: FUN123', max_length=20, unique=True, verbose_name='c\xf3digo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.BigIntegerField(blank=True, null=True, verbose_name='telefone')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='data de nasc.')),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Supervisor'), (2, 'Secret\xe1rio'), (3, 'T\xe9cnico')], default=3, verbose_name='tipo de usu\xe1rio')),
            ],
            options={
                'verbose_name': 'usu\xe1rio',
                'verbose_name_plural': 'usu\xe1rios',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='sobrenome')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, verbose_name='sexo')),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Vi\xfavo')], max_length=10, verbose_name='estado civil')),
                ('cpf', models.BigIntegerField(unique=True, verbose_name='CPF')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='c\xf3digo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_tipo_logradouro', models.CharField(choices=[('rua', 'Rua'), ('avenida', 'Avenida'), ('travessa', 'Travessa')], max_length=10, verbose_name='Tipo Logradouro')),
                ('endereco_logradouro', models.CharField(max_length=80, verbose_name='Logradouro')),
                ('endereco_numero', models.IntegerField(verbose_name='N\xfamero')),
                ('endereco_complemento', models.CharField(blank=True, max_length=45, verbose_name='Complemento')),
                ('endereco_bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('endereco_cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('endereco_estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amap\xe1'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Esp\xedrito Santo'), ('GO', 'Goi\xe1s'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Par\xe1'), ('PB', 'Para\xedba'), ('PR', 'Paran\xe1'), ('PE', 'Pernambuco'), ('PI', 'Piau\xed'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rond\xf4nia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'S\xe3o Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('endereco_cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
            ],
            options={
                'ordering': ['endereco_tipo_logradouro'],
                'verbose_name': 'Endere\xe7o',
                'verbose_name_plural': 'Endere\xe7os',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.Endereco', verbose_name='endere\xe7o'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Endereco', verbose_name='endere\xe7o'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
