# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.BigIntegerField(unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.BigIntegerField(blank=True, null=True, verbose_name='telefone')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='data de nasc.')),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='c\xf3digo')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Supervisor'), (2, 'Secret\xe1rio'), (3, 'T\xe9cnico')], default=3, verbose_name='tipo de usu\xe1rio')),
            ],
            options={
                'verbose_name': 'usu\xe1rio',
                'verbose_name_plural': 'usu\xe1rios',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'bairro',
                'verbose_name_plural': 'bairros',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=30, verbose_name='sobrenome')),
                ('cpf', models.BigIntegerField(unique=True, verbose_name='CPF')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='c\xf3digo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='logradouro')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.Bairro')),
            ],
            options={
                'ordering': ('bairro', 'nome'),
                'verbose_name': 'logradouro',
                'verbose_name_plural': 'logradouros',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'munic\xedpio',
                'verbose_name_plural': 'munic\xedpios',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('nome',),
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
            },
        ),
        migrations.AddField(
            model_name='municipio',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.UF', verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Logradouro', verbose_name='endere\xe7o'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairros', to='cadastro.Municipio', verbose_name='munic\xedpio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Logradouro', verbose_name='endere\xe7o'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
