# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20160219_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bairro',
            options={'ordering': ('nome',), 'verbose_name': 'bairro', 'verbose_name_plural': 'bairros'},
        ),
        migrations.AlterModelOptions(
            name='logradouro',
            options={'ordering': ('bairro', 'nome'), 'verbose_name': 'logradouro', 'verbose_name_plural': 'logradouros'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ('nome',), 'verbose_name': 'munic\xedpio', 'verbose_name_plural': 'munic\xedpios'},
        ),
        migrations.AlterModelOptions(
            name='uf',
            options={'ordering': ('nome',), 'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'usu\xe1rio', 'verbose_name_plural': 'usu\xe1rios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='dataCadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(max_length=30, verbose_name='sobrenome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='telefone'),
        ),
    ]
